server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**
        - id: college-service
          uri: lb://college-service
          predicates:
            - Path=/api/college/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
