spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: madasumanichandu79@gmail.com
    password: emcw muqk ighg stvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
