server:
  port: 8083

spring:
  application:
    name: email-service
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: madasumanichandu79@gmail.com
    password: emcw muqk ighg stvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
